### ISSUE TITLE
Cannot set the existing ARC / AUT numbers

### ISSUE THREAD

**Issue by Calen4ss** [WhatTheBlock/MapleStory-ARC-Calculator#4]
On AUT page, now i can only set the AUT levels, but cannot input the existing numbers. is that a bug?
![QQ截图20230620120251](https://github.com/WhatTheBlock/MapleStory-ARC-Calculator/assets/87116066/1809b3a9-cbdc-4751-a094-57c87cbf7d01)

**Comment by WhatTheBlock** [comment]
fixed.
